version: "3"
services:
  coodinator:
    image: trinodb/trino:356
    container_name: coodinator
    hostname: trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino/:/etc/trino/
    networks:
      - trino
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - trino
networks:
  trino:
    driver: bridge
